server:
  port: 8762

spring:
  application:
    name: zuul-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignoredServices: '*'
  routes:
    product-service:
      path: /product/**
      service-id: product-service
    customers-service:
      path: /customers/**
      service-id: customers-service
    order-service:
      path: /order/**
      service-id: order-service
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 6000

hystrix:
  command:
    default:
    execution:
    isolation:
    thread:
    timeoutInMilliseconds: 1100